name: kiddo_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_timer_countdown: ^1.0.7
  provider: ^6.1.5+1
  dio: ^5.8.0+1
  flutter_animate: ^4.5.2
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  permission_handler: ^12.0.1
  mqtt_client: ^9.6.1
  flutter_local_notifications: ^18.0.1
  razorpay_flutter: ^1.3.7
  intl: ^0.19.0
  geocoding: ^3.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/kt_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/kt_logo.png"
  remove_alpha_ios: true
  remove_alpha_android: true
  adaptive_icon_background: "#d4e9f7"
  adaptive_icon_foreground: "assets/images/kt_logo.png"
